#!/bin/bash

function match {
	if [[ $mes =~ ^(feature|bugfix)\/(TVN[A-Z]+\-[0-9]+).* ]]; then
		return 0
	fi

	return 1
}

mes=$(git rev-parse --abbrev-ref HEAD)
match $mes	

if  [[ $? -eq 0 ]]; then
	echo "${BASH_REMATCH[2]} | $(cat $1)" > "$1"
fi
