#!/bin/bash

CURRENT_DIRECTORY=`pwd`
GIT_HOOKS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_DIRECTORY="$GIT_HOOKS_DIR/../.."

cd $PROJECT_DIRECTORY;
PHP_CS_FIXER="vendor/bin/php-cs-fixer"
PHP_CODE_SNIFFER="vendor/bin/phpcs"
HAS_PHP_CS_FIXER=false
HAS_PHP_CODE_SNIFFER=false
FILES=$(git status --porcelain | grep -e '^[(A| )M]\(.*\).php$' | cut -c 3-)
STATUS=1
RED='\e[0;31m'
GREEN='\e[0;32m'
COLOR_RESET='\e[m'

for FILE in $SFILES
do
	php -l -d display_errors=0 $PROJECT/$FILE
	if [ $? != 0 ]
	then
		echo "Fix the error before commit."
		exit 1
	fi
	FILES="$FILES $PROJECT/$FILE"
done

if [ -x "$PHP_CS_FIXER" ]; then
    HAS_PHP_CS_FIXER=true
fi

if [ -x "$PHP_CODE_SNIFFER" ]; then
    HAS_PHP_CODE_SNIFFER=true
fi


if [ -L "$HOME/.config/composer/$PHP_CS_FIXER" ]; then
	PHP_CS_FIXER="$HOME/.config/composer/$PHP_CS_FIXER"
	HAS_PHP_CS_FIXER=true
fi	

if $HAS_PHP_CS_FIXER; then
    ${PHP_CS_FIXER} fix $FILES --rules=@Symfony --config=.php_cs 2>/dev/null
else
    echo ""
    echo "Please install php-cs-fixer, e.g.:"
    echo "composer require --dev friendsofphp/php-cs-fixer:2.0.0-RC"
    exit $?
fi

if $HAS_PHP_CODE_SNIFFER; then
    git status --porcelain | grep -e '^[ M]\(.*\).php$' | cut -c 4- | while read line; do
        ${PHP_CODE_SNIFFER} --standard=PSR2 $FILES;
    done
else
    echo ""
    echo "Please install php-code-sniffer:"
    echo "composer global require squizlabs/php_codesniffer"
    echo ""
    exit $?
fi

STATUS=$?
if [ $STATUS -gt 0 ]; then
    echo -e "$RED \U2717 Please fix the errors above."
else
    echo -e "$GREEN \U2713 Looking good."
fi

cd $CURRENT_DIRECTORY;

exit $STATUS;


