#!/bin/bash

CURRENT_DIRECTORY=`pwd`
GIT_HOOKS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_DIRECTORY="$GIT_HOOKS_DIR/../.."

cd $PROJECT_DIRECTORY;
PHP_CS_FIXER="vendor/bin/php-cs-fixer"
PHP_CODE_SNIFFER="vendor/bin/phpcs"
HAS_PHP_CS_FIXER=false
HAS_PHP_CODE_SNIFFER=false
STATUS=1
RED='\e[0;31m'
GREEN='\e[0;32m'
COLOR_RESET='\e[m'


# @TODO support for files from cli args

echo "Checking PHP Lint..."
php -l -d display_errors=0 $PROJECT/$FILE
if [ $? != 0 ]
then
    echo -e "$RED \U2717 Fix errors."
    exit 1
fi


FILES=$(git status --porcelain | grep -e '^[(A| )M]\(.*\).php$' | cut -c 3-)

if [ ${#FILES} -eq 0 ]; then
    exit 0
fi

if [ -x "$PHP_CS_FIXER" ]; then
    HAS_PHP_CS_FIXER=true
fi

if [ -x "$PHP_CODE_SNIFFER" ]; then
    HAS_PHP_CODE_SNIFFER=true
fi

if [ -L "$HOME/.config/composer/$PHP_CS_FIXER" ]; then
	PHP_CS_FIXER="$HOME/.config/composer/$PHP_CS_FIXER"
	HAS_PHP_CS_FIXER=true
fi	

if $HAS_PHP_CS_FIXER; then
    ${PHP_CS_FIXER} fix $FILES --rules=@Symfony --config=.php_cs 2>/dev/null
else
    echo ""
    echo "Please install php-cs-fixer, e.g.:"
    echo "composer require --dev friendsofphp/php-cs-fixer:2.0.0-RC"
    exit $?
fi

if $HAS_PHP_CODE_SNIFFER; then
    ${PHP_CODE_SNIFFER} --standard=PSR2 $FILES;
else
    echo ""
    echo "Please install php-code-sniffer:"
    echo "composer global require squizlabs/php_codesniffer"
    echo ""
    exit $?
fi

STATUS=$?
if [ $STATUS -eq 0 ]; then
    echo -e "$GREEN \U2713 Looking good."
else
    echo -e "$RED \U2717 Please fix the errors above."
fi

cd $CURRENT_DIRECTORY;

exit $STATUS;


